import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '@/styles/Checkout.module.css'
import Layout from '@/components/layout'
import Cart from "@/components/cart"

import { useState } from 'react';
import { getDatabase, ref, push } from "firebase/database";
import firebase_app from "@/components/config";
import { useRouter } from 'next/router';

const db = getDatabase(firebase_app);
const inter = Inter({ subsets: ['latin'] })

function Checkout(pageProps) {
    const [formData, setFormData] = useState({});
    const router = useRouter();

    const handleInputChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
      };
    
      const handleSubmit = async (e) => {
        e.preventDefault();
        
        // Récupérer les articles du panier depuis le localStorage
        const cartItems = JSON.parse(localStorage.getItem('cart')) || [];
        
        // Créer l'objet de commande
        const order = {
          ...formData,
          items: cartItems,
          date: new Date().toISOString(),
          status: 'en attente'
        };
    
        try {
          // Ajouter la commande à la base de données Firebase
          const ordersRef = ref(db, 'orders');
          await push(ordersRef, order);
    
          // Vider le panier
          localStorage.removeItem('cart');
    
          // Rediriger vers une page de confirmation
          router.push('/order-confirmation');
        } catch (error) {
          console.error("Erreur lors de la création de la commande:", error);
          // Gérer l'erreur (par exemple, afficher un message à l'utilisateur)
        }
      };
  return (
    <>
      <Head>
        <title>Nextjs E-Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.mainSection}>
            <form onSubmit={handleSubmit} className={styles.form}>
                <h1>CHECKOUT</h1>
                <div>
                <h3>BILLING DETAILS</h3>
                <div className={styles.formdiv}>
                <div>
                    <label htmlFor="name">Name</label>
                    <input type="text" name="name" id="name" onChange={handleInputChange} required />
                </div>
                <div>
                    <label htmlFor="email">Email Address</label>
                    <input type="email" name="email" id="email" onChange={handleInputChange} required />
                </div>
                <div>
                    <label htmlFor="phone">Phone Number</label>
                    <input type="tel" name="phone" id="phone" onChange={handleInputChange} required />
                </div>
                </div>
            </div>
            <div>
                <h3>SHIPPING INFO</h3>
                <div className={styles.formdiv}>
                <div>
                    <label htmlFor="address">Address</label>
                    <input type="text" name="address" id="address" onChange={handleInputChange} required />
                </div>
                <div>
                    <label htmlFor="zipcode">ZIP Code</label>
                    <input type="text" name="zipcode" id="zipcode" onChange={handleInputChange} required />
                </div>
                <div>
                    <label htmlFor="city">City</label>
                    <input type="text" name="city" id="city" onChange={handleInputChange} required />
                </div>
                <div>
                    <label htmlFor="country">Country</label>
                    <input type="text" name="country" id="country" onChange={handleInputChange} required />
                </div>
                </div>
            </div>
            <div>
                <h3>PAYMENT DETAILS</h3>
                <div className={styles.formdiv}>
                <div>
                    <label htmlFor="paymentMethod">Payment Method</label>
                    <select name="paymentMethod" id="paymentMethod" onChange={handleInputChange} required>
                    <option value="e-Money">e-Money</option>
                    <option value="Cash on Delivery">Cash on Delivery</option>
                    </select>
                </div>
                <div>
                    <label htmlFor="emoneynumber">e-Money Number</label>
                    <input type="text" name="emoneynumber" id="emoneynumber" onChange={handleInputChange} placeholder='24304530' />
                </div>
                <div>
                    <label htmlFor="emoneypin">e-Money PIN</label>
                    <input type="text" name="emoneypin" id="emoneypin" onChange={handleInputChange} placeholder='6891' />
                </div>
                </div>
            </div>
            <button type="submit" className={styles.submitButton}>CONTINUE & PAY</button>
            </form>
            <Cart/>
        </main>
      </Layout>
    </>
  )
}

export default Checkout;
